package com.szmtjk.web.controller;

import com.szmtjk.business.model.FileImportStatus;
import com.szmtjk.business.model.FileImportStatusQuery;
import com.szmtjk.web.controller.base.BaseCRUDController;

/**
 * auto generated by code helper on 2019-03-04.
 */
//@RestController
//@RequestMapping("/fileImportStatus")
public class FileImportStatusController extends BaseCRUDController<FileImportStatus, FileImportStatusQuery> {

}