spring:
  profiles:
    active: dev
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
  pid:
    file: pid.file

server:
  port: 16722
  contextPath: /xyl

fee:
  rule: 0
xyl:
  upload:
    baseDir: /data/pic/upload

# OAuth weixin
oauth:
  weixin:
    appId: wx716e867a8dfc27bb
    secretKey: 39a1e707862681e0690dfb6336e6dc87

wechat:
  appSecretConfigList:
    -
      appType: 1  # 公众号
      appId: wx0c7afe647c20cd75
      appSecret: 0224b50e3edb78091fbc1f3f3ee4f742

excel:
  reservation:
    zipUploadDir: /data/excel/reservation/zipUpload
    unzippedDir: /data/excel/reservation/unzipped
    invalidFileDir: /data/excel/reservation/invalid
  report:
    zipUploadDir: /data/excel/report/zipUpload
    unzippedDir: /data/excel/report/unzipped
    invalidFileDir: /data/excel/report/invalid

# Different profiles' configuration